services:

  mysql:
    image: mysql:8.0
    container_name: yw_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_boot_jpa_docker_jenkins_pipeline
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
    - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spring_boot_jpa_docker_jenkins_pipeline
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
